
#
# How to install wild
# * cargo install --git https://github.com/davidlattimore/wild --tag __VERSION__ wild-linker
#
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]
